In [1]:
import numpy as np

code_olympics = np.array([[1,1,0,0,0,0,1,1],
                          [1,1,0,1,1,0,1,1],
                          [0,0,0,1,1,0,0,0],
                          [1,1,0,1,1,0,1,1],
                          [1,1,0,0,0,0,1,1]])

team_per_row = {}

def parse_row(row):
    np

[[1 1 0 0 0 0 1 1]
 [1 1 0 1 1 0 1 1]
 [0 0 0 1 1 0 0 0]
 [1 1 0 1 1 0 1 1]
 [1 1 0 0 0 0 1 1]]
