In [41]:
import numpy as np

code_olympics = np.array([[1,1,0,0,0,0,1,1],
                          [1,1,0,1,1,0,1,1],
                          [0,0,0,1,1,0,0,0],
                          [1,1,0,1,1,0,1,1],
                          [1,1,0,0,0,0,1,1]])


def teamify(people):
    teams = {}
    team_num = 0
    i = 0
    while i+1 < len(people):
        if abs(people[i] - people[i+1]) == 1:
            if team_num in teams:
                teams[team_num].append(people[i], people[i+1])
            else:
                teams[team_num] = [people[i], people[i+1]]
        else:
            team_num += 1
        i += 1
    
    return teams

co_teams = []
def parse_row(row, row_num):
    people = row_num*len(row) + np.where(row)[0]
    print(people)
    co_teams.append(teamify(people))

co_teams_grouped = {}
def parse_matrix(matrix):
    for i, row in enumerate(matrix):
        parse_row(row, i)
    
    print(co_teams)

    for c in range(len(co_teams)):
        print(co_teams[c])

        # for tn, team in enumerate(co_teams[c].values()):
        #     print(tn)
        #     print(team)
        #     for team2 in co_teams[c+1].values(): 
        #         if team[0] == (team2[0] % matrix.shape[0]):
        #             if tn in co_teams_grouped:
        #                 co_teams_grouped[tn].append(team + team2[0])
        #             else:
        #                 co_teams_grouped[tn] = team + team2[0]


parse_matrix(code_olympics)

[0 1 6 7]
[ 8  9 11 12 14 15]
[19 20]
[24 25 27 28 30 31]
[32 33 38 39]
[{0: [0, 1], 1: [6, 7]}, {0: [8, 9], 1: [11, 12], 2: [14, 15]}, {0: [19, 20]}, {0: [24, 25], 1: [27, 28], 2: [30, 31]}, {0: [32, 33], 1: [38, 39]}]
{0: [0, 1], 1: [6, 7]}
{0: [8, 9], 1: [11, 12], 2: [14, 15]}
{0: [19, 20]}
{0: [24, 25], 1: [27, 28], 2: [30, 31]}
{0: [32, 33], 1: [38, 39]}
